id: security-best-practices
name: Security & Code Quality
description: Security frameworks, accessibility guidelines, performance optimization, and code quality best practices for building secure, maintainable, and high-performance applications.
tags: [security, accessibility, performance, code-quality, owasp, a11y, optimization, best-practices]
items:

  - path: instructions/performance-optimization.instructions.md
    kind: instruction
    kind: instruction


display:
  ordering: alpha
  show_badge: true
